FORMAT: 1A
HOST: http://localhost:3000

# Target

TargetApi is a API REST proyect, is design for users and admins, users can create targets of a topic and match with other users with similar topics interest in the same area, and create a chat between them.

# Group Target Controller

## Find a Target [/api/v1/targets/{id}]

### Get a Target [GET]

+ Request (application/json)

    + Parameters
        + id (integer, required)
    + Headers

            access-token: sO2bm_Bpdyoo8r78jZ-fqg
            client: QADgNCWRJj0LyRruqzYbBg
            uid: test@test.com    

+ Response 404

+ Response 200 (application/json)

    + Headers

            access-token: sO2bm_Bpdyoo8r78jZ-fqg
            client: QADgNCWRJj0LyRruqzYbBg
            uid: test@test.com

    + Body

            {
                "target": {
                    "id": 27,
                    "topic_id": 1,
                    "user_id": 1,
                    "title": "Target numero 27",
                    "radius": 100,
                    "latitude": "33.22",
                    "longitude": "45.44"
                }
            }
    
## Create a Target [/api/v1/targets]

### Create a Target [POST]

+ Request (application/json)

   + Headers

            access-token: sO2bm_Bpdyoo8r78jZ-fqg
            client: QADgNCWRJj0LyRruqzYbBg
            uid: test@test.com

    + Body

            {
                "target": {
                    "topic_id": 1,
                    "title": "Target numero 27",
                    "radius": 100,
                    "latitude": "33.22",
                    "longitude": "45.44"
                }
            }

+ Response 400

+ Response 201 (application/json)

    + Headers

            access-token: sO2bm_Bpdyoo8r78jZ-fqg
            client: QADgNCWRJj0LyRruqzYbBg
            uid: test@test.com

    + Body

            {
                "target": {
                    "id": 40,
                    "topic_id": 1,
                    "user_id": 21,
                    "title": "Target numero 28",
                    "radius": 100,
                    "latitude": "33.22",
                    "longitude": "45.44"
                }
            }

# Group User
## Login [/api/v1/users/sign_in]

### Login [POST]

+ Request (application/json)

    + Body

            {
              "user":
                {
                  "email": "test@test.com",
                  "password": "password"
                }
            }


+ Response 401


+ Response 200 (application/json)
    + Headers

            access-token: sO2bm_Bpdyoo8r78jZ-fqg
            client: QADgNCWRJj0LyRruqzYbBg
            expiry: 1489009792
            uid: test@test.com


    + Body

            {
                "user": {
                    "id": 21,
                    "email": "antonieta.alvarez+114@rootstrap.com",
                    "provider": "email",
                    "full_name": "Juan Test",
                    "gender": "female",
                    "uid": "antonieta.alvarez+114@rootstrap.com",
                    "created_at": "2019-12-02T17:33:08.614Z",
                    "updated_at": "2019-12-06T19:24:32.242Z",
                    "allow_password_change": true
                }
            }

## Registration [/api/v1/users]

### Sign up [POST]

+ Request (application/json)

    + Body

            {
              "user":
                {
                  "email":"antonieta.alvarez+118@rootstrap.com",
                  "password":"123456",
                  "password_confirmation":"123456",
                  "gender":"female",
                  "full_name":"Juan Test"
                }
            }


+ Response 422


+ Response 200 (application/json)

    + Body

            {
                "user": {
                    "id": 21,
                    "email": "antonieta.alvarez+114@rootstrap.com",
                    "provider": "email",
                    "full_name": "Juan Test",
                    "gender": "female",
                    "uid": "antonieta.alvarez+114@rootstrap.com",
                    "created_at": "2019-12-02T17:33:08.614Z",
                    "updated_at": "2019-12-06T19:24:32.242Z",
                    "allow_password_change": true
                }
            }


## Reset password [/api/v1/users/password]

### Ask for reset passowrd [POST]

Use this route to send a password reset confirmation email.

+ Request (application/json)
    + Body

            {
              "email": "test@test.com",
              "redirect_url": "http://www.example.com"
            }

+ Response 404

+ Response 200 (application/json)
    + Body

            {
              "success": true,
              "message": "An email has been sent to 'test@test.com' containing instructions for resetting your password."
            }

### Reset passowrd [PATCH]

Use this route to change user's passwords after open the link that was sended in the email.

+ Request (application/json)

    + Headers

            access-token: sO2bm_Bpdyoo8r78jZ-fqg
            client: QADgNCWRJj0LyRruqzYbBg
            uid: test@test.com    

    + Body

            {
              "password": "12345678",
              "password_confirmation": "12345678"
            }

+ Response 422

+ Response 200 (application/json)
    + Headers

            access-token: sO2bm_Bpdyoo8r78jZ-fqg
            client: QADgNCWRJj0LyRruqzYbBg
            expiry: 1489009792
            uid: test@test.com

    + Body

            {
                    "user":
                {
                  "id": 28,
                  "email": "test@test.com",
                  "full_name": "Juan Test",
                  "created_at": "2019-12-06T20:25:54.476Z",
                  "updated_at": "2019-12-06T20:25:54.476Z",
                  "provider": "email",
                  "gender": "female",
                  "uid": "1234567890",
                   "allow_password_change": false
                }
            }