SERVER_URL: 'http://localhost:3000'
PASSWORD_RESET_URL: 'http://localhost:3000'
MAILER_HOST: 'localhost:3000'
S3_SECRET_KEY: 'secret_key'
S3_REGION: 'region'
S3_BUCKET: 'bucket'
S3_ACCESS_ID: 'access_id'
